config/routes.rb
Rails.application.routes.draw do
  get 'readiness_events/index'

  root 'pages#login' # rout
  get 'home'    => 'pages#home'
  
  get 'newcontent' => 'pages#newcontent'
  post 'pages/savecontent' => 'pages#savecontent'
  post 'addfolder' => 'pages#addfolder'
  post 'geturlinfo' => 'pages#geturlinfo'
  
  get 'viewcontent' => 'pages#viewcontent'
  get 'readinessevent' => 'pages#readinessevent'
  post 'pages/save_readiness_event' => 'pages#save_readiness_event'
  patch 'pages/save_readiness_event' => 'pages#save_readiness_event'
  
  get 'checkreadiness' => 'pages#checkreadiness'
  post 'save_check_readiness' => 'pages#save_check_readiness'
  get 'cancelreadiness' => 'pages#cancelreadiness'
  
  get 'readinessactivity' => 'pages#readinessactivity'
  get 'userlist' => 'pages#userlist'
  get 'faqlist' => 'pages#faqlist'
  post 'pages/savefaq' => 'pages#savefaq'
  
  get 'dashboard' => 'pages#dashboard'
  
  resources :content_items  , only: [:index, :edit, :update, :destroy]
  resources :readiness_events  , only: [:index, :edit, :update, :destroy]
  
  #salesforce authentication
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'pages#logout', as: 'signout', via: [:get, :post]

  
end

app/views/pages/addfolder.js.erb
<% @folders.each do |f|%>
  console.log("<%= f.name %>")
  var newFolder = new Option("<%= f.name %>", "<%= f.name %>");
  $(".folderlist").append(newFolder);
<% end %>
$(".folder_field").val('');
$('.closemodal').click();

app/views/pages/checkreadiness.html.erb
<% provide(:url, @content_item.url) %>
<% provide(:title, @content_item.name) %>
<% provide(:image, @content_item.thumbnail ) %>
<% provide(:description,@content_item.description) %>
<style>
 .radio-inline, .checkbox-inline, .radio label, .checkbox label {
   padding-left: 0;
  }

  .iCheck-margin {
   margin-right: 5px;
  }
  
  body{
   padding-top: 75px !important;
   background-color:lightgrey !important;
  }
  .content{
   background-color:#fff !important;
  }

  .backimg{
   background-image:url(<%= asset_path("check.png") %>) !important;
   border:0 !important;
  }
  .iradio_square-blue.checked.disabled {
    background-position: -168px 0 !important;
}
.red{
 color:red;
 font-weight:bold;
}
.green{
 color:green;
 font-weight:bold;
}
</style>

<div class="container"> 
  
  <div class="row content ">
   <br><br><br>
   <div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-12 col-xs-12 form-group">
    <% if @content_item.attachment_url.blank? %>
 				<iframe id="videoFrame" frameborder="0" allowfullscreen src="<%= @content_item.url %>" height="440" width="100%" style="border:1px solid lightgrey">
     </iframe>
			<% elsif @content_item.attachment_url.include? ".pdf" %>
				<a href="<%= @content_item.attachment_url %>" target="_blank"><%= image_tag("Pdf.png",  :class =>"img-responsive addNew ") %></a>
			<% elsif @content_item.attachment_url.include? ".ppt" %>
    <a href="<%= @content_item.attachment_url %>" target="_blank" ><%= image_tag("ppt.png",  :class =>"img-responsive addNew ") %></a>
   <% end %>
   <h4><a style="color:#72B5E8" href="<%= @content_item.url %>"><%= @content_item.name %></a></h4>
    <p><%= @content_item.description %></p>
   </div>
  </div>
  
  <div class="row" style="background-color:lightgrey; height:10px">
   
  </div>
  <% if @is_error == true %>
  <div class="row content">
   <div class="col-lg-1 col-md-1 col-sm-1 col-xs-1"></div>
   <div class="col-lg-10 col-md-10 col-sm-10 col-xs-10">
    <br>
    <div class="alert alert-danger">You already have done three attempts, so you are not allowed to do more attempts.</div>
   </div>
   <div class="col-lg-1 col-md-1 col-sm-1 col-xs-1"></div>
  </div>
  
  <div class="row" style="background-color:lightgrey;  height:10px">
   
  </div>
  
  <% end %>
  <% if @is_error == false %>
  <% if @questions.size >0 %>
  <div class="row content">
   <div class="col-lg-5 col-lg-offset-1 col-md-offset-1 col-md-5 col-sm-7 col-xs-8">
    <h3> 
     <input type="checkbox" checked id="read" /> Readiness Check
    </h3>
   </div>
   <div class="col-lg-5 col-lg-offset-1 col-md-offset-1 col-md-5 col-sm-5 col-xs-4" style="text-align:right;padding-top:10px">
    <% if @showresult==true %>
    <h4> You have scored <br/> <span style="font-weight:600;font-size:24px"><%= @points %> Points</span></h4>
    <% end %>
    
   </div>
  </div>
  <% end %>
  <div class="row" style="background-color:lightgrey;  height:10px">
   
  </div>
  
  <div class="row content questions">
   <div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-12 col-xs-12">
   <%= form_tag save_check_readiness_path :method => :post do %>  
     <% @count = 0 %>
     <% @questions.each do |question| %>
     <%= fields_for "answers[#{@count}]", @answers[@count] do |f1| %>
      <%= f1.hidden_field :question_id, :value =>question.id %>
      <div class="row">
       <div class="col-xs-12">
        <h4><%= @count + 1 %>. <%= question.name %></h4>
        <div class="form-group <%= get_answer_css(@showresult,@answers[@count].given_answer,question.answer,'A') %>"> 
          <%= f1.radio_button :given_answer, "A" ,:disabled => @showresult == true  %>
          <%= question.choice_a %>
        </div>
        <div class="form-group <%= get_answer_css(@showresult,@answers[@count].given_answer,question.answer,'B') %>" > 
         <%= f1.radio_button :given_answer, "B" ,:disabled => @showresult == true  %><%= question.choice_b %>
        </div>
        <div class="form-group <%= get_answer_css(@showresult,@answers[@count].given_answer,question.answer,'C') %>" > 
         <%= f1.radio_button :given_answer, "C" , :disabled => @showresult == true%><%= question.choice_c %>
        </div>
        <div class="form-group <%= get_answer_css(@showresult,@answers[@count].given_answer,question.answer,'D') %>" > 
         <%= f1.radio_button :given_answer, "D" ,:disabled => @showresult == true %><%= question.choice_d %>
        </div>    
        <hr>
      </div>
     </div>
     <% end %>
     <% @count = @count+1 %>
     <% end %>
     
     <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-center" style="padding-top:5px">
      <% if @showresult == false %>
       <% if @questions.size > 0 %>
       <button class="btn btn-primary">Done</button> &nbsp;
       <% end %>
       <a href="/cancelreadiness?id=<%= @readiness_event.id %>"><button type="button" class="btn btn-default">Cancel</button></a>
      <% else %>
      <%= link_to '<button type="button" class="btn btn-primary">Close</button>'.html_safe, readinessactivity_path, class:"myBtn" %>
      <% end %>
      <div class="form-group"></div>
     </div>
    <% end %>
  </div>
  </div>
  <% end %>
  <br><br><br>
  
 </div>
 
 <script>
 $(document).ready(function () {
   // Init check box and radio button ui 
   initCheckbox();     
   
  });
 
  function initCheckbox(){
   $('input').iCheck({
    checkboxClass: 'icheckbox_minimal-blue',
    radioClass: 'iradio_minimal-blue',
    checkboxClass: 'icheckbox_square-blue iCheck-margin',
    radioClass: 'iradio_square-blue iChk iCheck-margin'
   });
   
   $('#read').parent().css({'height':'50px', 'width':'50px', 'background':'#fff','border':'2px solid green', 'border-radius':'25px'});
   $('#read').parent().toggleClass("backimg");  
   $('input#read').on('ifChanged', function (event) {
    $('.questions').toggle();    
    $('#read').parent().toggleClass("backimg");   
   });
  }
 </script>

app/views/pages/faqlist.html.erb
<style>
.required{
		border-color: #a94442;
	}
</style>
<br>
<div class="container-fluid">
 <div class="row">
   <div class="col-xs-12 col-md-offset-2 col-md-8">
     <%= form_for @faq, :url => {:action => "savefaq"} do |f| %>
     <div class="form-group">
        <label for="title" class="required">Question</label>
        <%= f.text_field :question,class: 'form-control myRequired', :placeholder => "Question" %>
      </div>
      <div class="form-group">
        <label for="description">Tags</label>
        <input id="input-tag" class="form-control" type="text" data-role="tagsinput" value="<%= @faq.tags %>"/>
        <%= f.hidden_field :tags ,class: 'tags_field' %>
      </div>
      
      <button type="submit" onclick="return validate()"  class="btn btn-primary">Save</button>
     <% end%>
     
     <hr>
     <h4>All FAQs</h4>
     <table class="table table-condensed">
       <thead>
         <tr>
           <th>Question</th>
           <th>Tags</th>
         </tr>
       </thead>
       <% @faq_list.each do |faq|%>
       <tr>
         <td><%= faq.question %> </td>
         <td><%= faq.tags %></td>
       </tr>
       <% end %>
     </table>
   </div>
  </div>
</div>
<script>
function validate(){
  settags();
  var isValid = true;
  $(".myRequired").each(function(){
    if($(this).val() ==''){
      isValid = false;
      $(this).addClass('required')
    }else{
      $(this).removeClass('required')
    }
  });
  return isValid;
}
function settags(){
  $(".tags_field").val($("#input-tag").val());
  console.log($(".tags_field").val())
}
</script>

app/views/pages/geturlinfo.js.erb
console.log('----');
var tags='';
<% @tages.each do |t| %>
var tag = "<%= t %>";
tag = tag.replace("&amp;","&");
tags += tag+",";
<% end %>
$(".tags").val(tags);
$(".bootstrap-tagsinput").find('input').val(tags);
$(".bootstrap-tagsinput").find('input').blur();
var summary = '';
<% @summary.each do |s| %>
summary += "<%= s %>\n";
<% end %>
if(summary!=''){
  summary =summary.substring(0,summary.length-1);
}
$(".content_description").val(summary);

app/views/pages/login.html.erb
<style>
body{
	background: #f1f1f1 none repeat scroll 0 0 !important;
}
.navbar{
  display:none;
}
</style>


<div class="container">
	<div class="row">
		<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-center">
			<br>
			<br>
			<h1 class="">Welcome to Salesica</h1>
			<br><br><br><br><br>
			<%= link_to '<button class="btn btn-primary btn-lg">Click here to login</button>'.html_safe, "/auth/salesforce", class:"myBtn" %>
			<br><br><br><br>
			
		</div>
		<% if @show_logout_message == true %>
		<div class="col-lg-4 col-sm-offset-3 col-md-4 col-md-offset-4 col-sm-6 col-xs-12 text-center">
			<div class="alert alert-success">You have Successfully Logged Out!</div>
    </div>
    <% end %>
	</div>
</div>

<iframe style="display:none;" src="<%= @logout_url %>"/>

app/views/pages/newcontent.html.erb
<style>
  .inner-addon { 
      position: relative; 
  }
  
  /* style icon */
  .inner-addon .glyphicon {
    position: absolute;
    padding: 10px;
    pointer-events: none;
  }
  
  /* align icon */
  .left-addon .glyphicon  { left:  0px;}
  .right-addon .glyphicon { right: 0px;}
  
  /* add padding  */
  .left-addon input  { padding-left:  30px; }
  .right-addon input { padding-right: 30px; }
  .vedioRow{
    padding:16px;
    paddin-top:0px;
    display:none;
  }
  .formSection{
    background-color:#EEEEEE;
    padding: 4px;
    margin-top:1px;
  }
  .btnPnl{
    margin-top:30px;
  }
  .btnPnl .btn{
      width: 125px;
  }
  .headerRow{
    background-color:#EEEEEE;
  }
    .menu ul {
      list-style-type: none;
      margin: 0;
      padding: 0;
      overflow: hidden;
      background-color: #f3f3f3;
    }
    
   .menu li {
        float: left;
        text-align:center;
    }
    
    .menu li a {
        display: inline-block;
        color: #666;
        text-align: center;
        padding: 10px 0px;
        text-decoration: none;
        text-transform: uppercase;
    }
    
    .menu li a:hover {
        background-color: #f3f3f3;
    }
    .collapseImg{
      display:none;
    }
    
    .menu ul {
      overflow: visible;
    }
    .menu li {
      padding:0;
    }
    .menu li a {
      display: block;
    }
      .active-dot{
      font-size:13px !important;
      display:none;
      left: 50%;
      margin-top: -8px;
      margin-left: -8px;
      position: absolute;
      top: 100%;	
      z-index: 999;
      }
      .navbar ul > .active > i {
        display:block;
        }
        .menu li {
         float: left;
         text-align: left;
        }
        .menu li a {
         padding: 10px 20px;
         text-align: left;  
        }
       .required{
      		border-color: #a94442;
      	}
      	.myicons{
      	  border: solid 1px lightgray;
          border-radius: 50%;
          height: 46px;
          padding: 4px;
          margin-left: 7px;
      	}
</style>
<div style="border:0px;margin-bottom:0px;" class="navbar menu">
  <ul class="row navbar-nav" style="width:100%">
    <li class="col-xs-12 col-md-offset-2 col-md-8">
     <a href="#">
      Add New 
     </a>
    </li>  
  </ul>
 </div>
 
<div class="container-fluid  myRequiredPnl" style="display:none">
  <div class="row">
   <div class="col-xs-12 col-md-offset-2 col-md-8">
     <div class="alert alert-danger">
        The form contains following error(s).
        <ul>
        </ul>
      </div>
   </div>
 </div>
</div> 
<%= form_for @content_item, :url => {:action => "savecontent"} do |f| %>
<div class="container-fluid">
 <div class="row">
   <div class="col-xs-12 col-md-offset-2 col-md-8">
      <button class="btn btn-primary" onclick="$('.filebutton').click();return false;">
        <span class="fa fa-upload"></span>  Upload file	
      </button>
      
      
      
      <%= image_tag("box.png",:class =>"myicons") %>
      <%= image_tag("drive.png",:class =>"myicons") %>
      <%= image_tag("salesforce.png" ,:class =>"myicons") %>
      
      <div class="fileName" style="padding-top:10px;font-weight:bold;"></div>
      <div style="display:none">
        <%= f.file_field :attachment , class: "filebutton" ,:input_html => {:onchange => "setFileName(this)"} %>
      </div>
      <br>
      Or
      <br><br>
    </div>
</div> 
<div class="row">
  <div class="col-xs-12 col-md-offset-2 col-md-8">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <% if @content_item.errors.any? %>
    <div>
      <div class="alert alert-danger">
        The form contains <%= pluralize(@content_item.errors.count, "error") %>.
        <ul>
      <% @content_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
      </div>
      
    </div>
  <% end %>
    
    <div class="form-group">
        <div class="input-group" style="width:100%">
      		<%= f.select(:content_type, ['Video', 'HTML','PDF','PPT','DOC'], {}, { :class => 'form-control contentType',:style=>'width:25%; float:left' }) %>
      		<div class="inner-addon left-addon" style="width:75%; float:right">
        		<i class="glyphicon glyphicon-search" style="position:absolute;z-index:99;"></i>
        		<%= f.text_field :url,class: 'form-control contentUrl', :placeholder => "URL" %>
      	  </div>
      	</div>
      	<div class="row vedioRow" >
          <div class="col-xs-12 col-md-10" style="padding:0px">
            <iframe id="contentFrame" width="100%" height="315" style="border: 0px;"
              src="">
            </iframe>
          </div>
        </div>
      </div>
      
      
      <div class="formSection">
        <div class="form-group">
          <label for="title" class="required">Title</label>
          <%= f.text_field :name,class: 'form-control myRequired', :placeholder => "Title" %>
        </div>
        <div class="form-group">
          <label for="description">Description</label>
          <%= f.text_area :description, class:'form-control content_description' %>
        </div>
        <div class="form-group">
          <label for="folder" class="required">Folder</label>
          <div class="input-group">
            <%= f.select(:folder, @all_folders.map{ |value| [ value.name, value.name ] }, {}, { :class => 'form-control folderlist' }) %>
            <a class="input-group-addon" data-toggle="modal" data-target="#modalAddFolder">
          	  <span class="glyphicon glyphicon-plus-sign" style="font-size:18px"></span>
            </a>
           </div>
        </div>
        
        <div class="form-group">
          <label for="tags">Tags</label>
            <input id="input-tag" class="form-control tags" type="text" data-role="tagsinput" value="<%= @content_item.tags %>"/>
          
          
          <%= f.hidden_field :tags ,class: 'tags_field' %>
        </div>
        
        <!--
        <div class="form-group">
          <label for="type">Type</label>
          <div class="radio">
            <label>
              <%= f.radio_button :content_type, "Whitepaper" %> Whitepaper
            </label>
          </div>
          <div class="radio">
            <label>
              <%= f.radio_button :content_type, "PPT" %> PPT
            </label>
          </div>
          <div class="radio">
            <label>
              <%= f.radio_button :content_type, "Customer Story" %> Customer Story
            </label>
          </div>
          <div class="radio">
            <label>
              <%= f.radio_button :content_type, "Competitive" %> Competitive
            </label>
          </div>
        </div>
        
        <div class="form-group">
          <label for="buyingstage">Buying Stage</label>
          <div class="radio">
            <label>
              <%= f.radio_button :buying_stage, "Whitepaper" %> Whitepaper
            </label>
          </div>
          <div class="radio">
            <label>
              <%= f.radio_button :buying_stage, "PPT" %> PPT
            </label>
          </div>
          <div class="radio">
            <label>
              <%= f.radio_button :buying_stage, "Customer Story" %> Customer Story
            </label>
          </div>
          <div class="radio">
            <label>
              <%= f.radio_button :buying_stage, "Competitive" %> Competitive
            </label>
          </div>
          
        </div>
        <div class="form-group">
          <label for="persona">Persona</label>
          <%= f.select(:persona, ['VP Sales', 'CMO', 'Product Marketing', 'Sales Ops', 'Sales Reps','Sales Managers', 'Solution Consultants'], {include_blank: '---None---'}, { :class => 'form-control' }) %>
        </div>
        <div class="form-group">
          <label for="persona">Industry</label>
          <%= f.select(:industry, ['Finance', 'Technology', 'Telco', 'Retail', 'Manufacturing','Pharma', 'Oil&Gas'], {include_blank: '---None---'}, { :class => 'form-control' }) %>
        </div>
        -->
      </div>
      
      <div class="formSection">
        <div>
          <b style="cursor:pointer" onclick="toggleMappingPnl()">
            <%= image_tag("maximize.png", alt: "Rails logo",class: "collapseImg") %><%= image_tag("expand.png", alt: "Rails logo",class: "expandImg") %>CRM Mapping</b>
        </div>
        <div class="crmmapping" style="margin-top:10px">
          <div class="form-group">
            <label for="persona">Opportunity Stage</label>
            <%= f.select(:stage, @opp_stage_list.map{ |value| [ value, value ] }, {include_blank: '---None---'}, { :class => 'form-control' }) %>
            
          </div>
        </div>
      </div>
      <div style="text-align:right" class="btnPnl">
        <button type="submit"  class="btn btn-primary" onclick="return validate();">Save</button>
        
        <%= link_to '<button type="button" class="btn btn-default">Cancel</button>'.html_safe, home_path, class:"myBtn" %>
      </div>
      <br><br>
     
  </div>
</div>
</div>


<% end %>


<div class="modal fade" id="modalAddFolder" tabindex="-1" role="dialog">
  <div class="modal-dialog" style="max-width:500px">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"> &times; </button>
        <h3 class="section-title-inner">Add Folder</h3>
      </div>
      <%= form_for(@new_folder, :url => {:action => "addfolder"} , remote: true) do |f| %>
      <div class="modal-body">   
        <div class="row">     
          <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="form-group">
               <label>Folder Name</label>
               <%= f.text_area :name, class:'form-control folder_field' , style:'height: 120px;', :placeholder => "Enter values for the folder picklist, with each value separated by a new line."%>
            </div>
          </div>
        </div>
       </div>
            
       <div class="modal-footer">
        <button type="submit" class="btn btn-primary" onclick="return validateFolderName();">Add</button>
        <button type="button" class="btn btn-default closemodal" data-dismiss="modal">Cancel</button>
       </div>
       <% end %>
      </div> 
    </div>
</div>

<div style="display:none">
  <%= form_for(@temp_content_item, :url => {:action => "geturlinfo"} , remote: true) do |f| %>
  <div class="modal-body">   
    <div class="row">     
      <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="form-group">
           <%= f.text_field :url, class:'form-control temp_url_field' %>
           <%= f.text_field :content_type, class:'form-control temp_type_field' %>
        </div>
      </div>
    </div>
   </div>
        
   <div class="modal-footer">
    <button type="submit" class="btn btn-primary temp_submit" >Submit</button>
   </div>
   <% end %>
</div>

<script>
    $(document).ready(function(){
      toggleNavmenu();
      toggleVedioPnl();
      
      $(".contentUrl").bind("change", function() {
        toggleVedioPnl();
      });
      $(".contentType").bind("change", function() {
        toggleVedioPnl();
      });
      
      $(".filebutton").bind("change", function() {
        setFileName();
      });
     
      
      $('.menu li a').click(function(){
        $('.menu li').removeClass('active');
        $(this).parent().addClass('active');
      });
       $("#input-tag").tagsinput('items');
    });
    
  function toggleVedioPnl(){
    if($(".contentUrl").val() != undefined && $(".contentUrl").val() !=''){
      $("#contentFrame").attr('src',$(".contentUrl").val());
      $(".vedioRow").show();
      if($(".contentType").val()!='Video'){
        //call api...
        $(".temp_url_field").val($(".contentUrl").val());
        $(".temp_type_field").val($(".contentType").val());
        $(".temp_submit ").click();
      }
    }else{
      $(".vedioRow").hide();
    }
  }
      
      
function toggleMappingPnl(){
  $(".crmmapping").toggle();
  $(".expandImg").toggle();
  $(".collapseImg").toggle();
}
function settags(){
  $(".tags_field").val($("#input-tag").val());
}
function setFileName(){
  var fileName='';
  var path = $('.filebutton').val();
  if(path !=''){
    var temp_list = path.split('\\');
    if(temp_list.length > 0){
      console.log(temp_list);
      fileName = temp_list[temp_list.length-1];
    }else{
      fileName = path;
    }
  }
  $(".fileName").text(fileName);
}

function validate(){
  settags();
  var isValid = true;
  var msg = '';
  $(".myRequired").each(function(){
    if($(this).val() ==''){
      isValid=false;
      msg = '<li>Title is reqired.</li>'
    }
  });
    
  if($('.filebutton').val() =='' && $(".contentUrl").val()==''){
    isValid=false;
    msg += '<li>Either upload a file or enter URL.</li>'
  }
  if(isValid==false){
    $(".myRequiredPnl").show();
    $(".myRequiredPnl ul").html(msg);
    window.scrollTo(0, 0);
  }else{
    $(".myRequiredPnl").hide();
  }
  return isValid;
}

function validateFolderName(){
   if($('.folder_field').val()=='' || $('.folder_field').val().trim() ==''){
       $('.folder_field').addClass("required");
       return false;
   }else{
     $('.folder_field').removeClass("required");
   }
   return true; 
  }
  
  // Clear folder name input after save folder or close modal
  $('#modalAddFolder').on('hide.bs.modal', function (e) {
     $('#folderName').val('');
  });
  
  
</script>

app/views/pages/userlist.html.erb
<style>
.navmenu-default .navmenu-nav.dropdown-menu, .navbar-default .navbar-offcanvas .navmenu-nav.dropdown-menu {
			background-color: #f8f8f8;
		}
		 .menu ul {
      list-style-type: none;
      margin: 0;
      padding: 0;
      overflow: hidden;
      background-color: #f3f3f3;
    }
    
   .menu li {
        float: left;
        
    }
   
		body{
			padding-top:55px !important;
		}
		.top-menu{
			background-color: #e7e7e7;
		}
		
		.content-row {
			background-color: #fff;
			margin-top: 20px;					
		}
		.content-info{
			min-height:70px;
		}
		.content-info h4 {
			color: black;
			font-size:17px;
		}
		.content-info h5 {
			color: appworkspace;
			font-size: 15px;
		}
		.img-icon {
			left: 50%;
			margin-left: -20px !important;
			margin-top: -20px !important;
			position: absolute;
			top: 50%;
			width: 40px;
			z-index: 99;
		}
</style>
<div style="border:0px;margin-bottom:0px;" class="navbar menu">
  <ul class="row navbar-nav" style="width:100%">
    <li class="col-xs-12 col-md-offset-2 col-md-8" style="font-weight:bold;padding: 10px 0px 10px 20px;font-size: 14px;">
     User List 
    </li>  
  </ul>
 </div>
<div class="container-fluid">
	<div class="row ">
		<div class="content-row col-xs-12 col-md-offset-2 col-md-8">
			<table class="table">
				<% @users.each do |user| %>
				<tr>
					<td>
						<div style="float:left"><img src="<%= user.profile_image %>" style="height:40px"></img></div>
						<div style="float:left;padding-left:10px">
						  <h4 style="margin-top:0px;margin-bottom:4px;"><%= user.name %></h4>
						  <% if user.allow_admin == true %>
						  Admin
						  <% end %>
						</div>
					</td>
				</tr>
				<% end %>
			</table>
		</div>
	</div>
</div>

app/views/pages/viewcontent.html.erb
<% provide(:url, @content_item.url) %>
<% provide(:title, @content_item.name) %>
<% provide(:image, @content_item.thumbnail ) %>
<% provide(:description,@content_item.description) %>
<br>
<div class="container-fluid">
  <div class="row vedioRow" >
    <div class="col-xs-12 col-md-offset-3 col-md-6" style="padding:0px">
      <iframe id="contentFrame" width="100%" height="315" style="border: 0px;"
        src="<%= @content_item.url %>">
      </iframe>
      <h4><%= @content_item.name %></h4>
      <p><%= @content_item.description %></p><br/>
      <center><%= link_to '<button type="button" class="btn btn-primary">Close</button>'.html_safe, home_path, class:"myBtn" %></center>
    </div>
    
  </div>
</div>