config/routes.rb
Rails.application.routes.draw do
  get 'readiness_events/index'

  root 'pages#login' # rout
  get 'home'    => 'pages#home'
  
  get 'newcontent' => 'pages#newcontent'
  post 'pages/savecontent' => 'pages#savecontent'
  post 'addfolder' => 'pages#addfolder'
  post 'geturlinfo' => 'pages#geturlinfo'
  
  get 'viewcontent' => 'pages#viewcontent'
  get 'readinessevent' => 'pages#readinessevent'
  post 'pages/save_readiness_event' => 'pages#save_readiness_event'
  patch 'pages/save_readiness_event' => 'pages#save_readiness_event'
  
  get 'checkreadiness' => 'pages#checkreadiness'
  post 'save_check_readiness' => 'pages#save_check_readiness'
  get 'cancelreadiness' => 'pages#cancelreadiness'
  
  get 'readinessactivity' => 'pages#readinessactivity'
  get 'userlist' => 'pages#userlist'
  get 'faqlist' => 'pages#faqlist'
  post 'pages/savefaq' => 'pages#savefaq'
  
  get 'dashboard' => 'pages#dashboard'
  
  resources :content_items  , only: [:index, :edit, :update, :destroy]
  resources :readiness_events  , only: [:index, :edit, :update, :destroy]
  
  #salesforce authentication
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'pages#logout', as: 'signout', via: [:get, :post]

  
end

app/models/content_item.rb
class ContentItem < ActiveRecord::Base
  belongs_to :user
  attr_accessor :vedio_id
  attr_accessor :item_type
  has_many :readiness_events , :dependent => :destroy
  
  mount_uploader :attachment, AttachmentUploader 
  
  validates :name, presence: true
  validates :folder, presence: true
  
  
  
  scope :including_all_tags, -> (tags) { where(tags.map { |tag| "(tags LIKE '%#{tag}%')" }.join(" AND ")) }
  scope :including_any_tags, -> (tags) { where(tags.map { |tag| "(tags LIKE '%#{tag}%')" }.join(" OR ")) }
  
  
  
  
  
  def self.search(query)
    #production
    where("name ilike ? ", "%#{query}%") 
    #sandbox
    #where("name like ? ", "%#{query}%")
  end
  
  
  def matching_tag_query(tags, condition_separator = 'OR')
    tags.map { |tag| "(tags LIKE '%#{tag}%')" }.join(" #{condition_separator} ")
  end
  
end

app/controllers/content_items_controller.rb
class ContentItemsController < ApplicationController
  before_action :set_content_item, only: [:show, :edit, :update, :destroy]
  include PagesHelper
  
  # GET /content_items
  # GET /content_items.json
  def index
    @content_items = ContentItem.order("created_at DESC")
    set_vediov_id(@content_items)
  end
  


  # GET /content_items/1
  # GET /content_items/1.json
  def show
  end

  # GET /content_items/new
  def new
    @content_item = ContentItem.new
  end

  # GET /content_items/1/edit
  def edit
    @all_folders = Folder.order("created_at ASC")
    get_stage_values   #inside page helper.rb
  end

  # POST /content_items
  # POST /content_items.json
  def create
    @content_item = ContentItem.new(content_item_params)
    if @content_item.save
      flash[:success] = "Content Item Create Successfully , You can create another Content Item."
      redirect_to index
    else
      render 'new'
    end
    
  end

  # PATCH/PUT /content_items/1
  # PATCH/PUT /content_items/1.json
  def update
      set_thumbnail_url( @content_item)
      if @content_item.update(content_item_params)
        redirect_to content_items_url
      else
        @all_folders = Folder.order("created_at ASC")
        get_stage_values   #inside page helper.rb
        render 'edit'
      end
    
  end

  # DELETE /content_items/1
  # DELETE /content_items/1.json
  def destroy
    @content_item.destroy
    respond_to do |format|
      format.html { redirect_to content_items_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_content_item
      @content_item = ContentItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def content_item_params
      params.require(:content_item).permit(:name, :url, :folder, :content_type, :tags,:industry,:buying_stage,:stage,:persona,:description)
    end
end

app/helpers/content_items_helper.rb
module ContentItemsHelper
end

app/views/content_items/_form.html.erb
<%= form_for(@content_item) do |f| %>
  <% if @content_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@content_item.errors.count, "error") %> prohibited this content_item from being saved:</h2>

      <ul>
      <% @content_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :folder %><br>
    <%= f.text_field :folder %>
  </div>
  <div class="field">
    <%= f.label :content_type %><br>
    <%= f.select(:content_type, ["Whitepaper", "PPT","Customer Story","Competitive"], {include_blank: '---None---'}, { :class => 'form-control' }) %>
    
  </div>
  <div class="field">
    <%= f.label :tags %><br>
    <%= f.text_field :tags %>
  </div>
  <div class="field">
    <%= f.label :stage %><br>
    <%= f.select(:stage, ['Finance', 'Technology', 'Telco', 'Retail', 'Manufacturing','Pharma', 'Oil&Gas'], {include_blank: '---None---'}, { :class => 'form-control' }) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/content_items/edit.html.erb
<style>
  .inner-addon { 
      position: relative; 
  }
  
  /* style icon */
  .inner-addon .glyphicon {
    position: absolute;
    padding: 10px;
    pointer-events: none;
  }
  
  /* align icon */
  .left-addon .glyphicon  { left:  0px;}
  .right-addon .glyphicon { right: 0px;}
  
  /* add padding  */
  .left-addon input  { padding-left:  30px; }
  .right-addon input { padding-right: 30px; }
  .vedioRow{
    padding:16px;
    paddin-top:0px;
    display:none;
  }
  .formSection{
    background-color:#EEEEEE;
    padding: 4px;
    margin-top:1px;
  }
  .btnPnl{
    margin-top:30px;
  }
  .btnPnl .btn{
      width: 125px;
  }
  .headerRow{
    background-color:#EEEEEE;
  }
    .menu ul {
      list-style-type: none;
      margin: 0;
      padding: 0;
      overflow: hidden;
      background-color: #f3f3f3;
    }
    
   .menu li {
        float: left;
        text-align:center;
    }
    
    .menu li a {
        display: inline-block;
        color: #666;
        text-align: center;
        padding: 10px 0px;
        text-decoration: none;
        text-transform: uppercase;
    }
    
    .menu li a:hover {
        background-color: #f3f3f3;
    }
    .collapseImg{
      display:none;
    }
    
    .menu ul {
      overflow: visible;
    }
    .menu li {
      padding:0;
    }
    .menu li a {
      display: block;
    }
      .active-dot{
      font-size:13px !important;
      display:none;
      left: 50%;
      margin-top: -8px;
      margin-left: -8px;
      position: absolute;
      top: 100%;	
      z-index: 999;
      }
      .navbar ul > .active > i {
        display:block;
        }
        .menu li {
         float: left;
         text-align: left;
        }
        .menu li a {
         padding: 10px 20px;
         text-align: left;  
        }
        
</style>
<div style="border:0px;margin-bottom:0px;" class="navbar menu">
  <ul class="row navbar-nav" style="width:100%">
       
    <li class="col-xs-12 col-md-offset-2 col-md-8">
   <a href="#">
    Add New 
   </a>
    </li>  
  </ul>
 </div>
<div class="container-fluid">
  
<div class="row">
  <div class="col-xs-12 col-md-offset-2 col-md-8">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <% if @content_item.errors.any? %>
    <div>
      <div class="alert alert-danger">
        The form contains <%= pluralize(@content_item.errors.count, "error") %>.
        <ul>
      <% @content_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
      </div>
      
    </div>
  <% end %>
    <%= form_for @content_item do |f| %>
      <div class="form-group">
        <div class="inner-addon left-addon">
          <i class="glyphicon glyphicon-search"></i>
          <%= f.text_field :url,class: 'form-control contentUrl', :placeholder => "URL" %>
        </div>
        <div class="row vedioRow" >
          <div class="col-xs-12 col-md-10" style="padding:0px">
            
              <% if @content_item.attachment_url.blank? %>
        				<iframe id="contentFrame" frameborder="0" allowfullscreen src="<%= @content_item.url %>" height="300" width="100%" style="border:1px solid lightgrey">
        				</iframe>
        			<% elsif @content_item.attachment_url.include? ".pdf" %>
        				<a href="<%= @content_item.attachment_url %>" target="_blank"><%= image_tag("Pdf.png",  :class =>"img-responsive addNew ") %></a>
        			<% elsif @content_item.attachment_url.include? ".ppt" %>
				        <a href="<%= @content_item.attachment_url %>" target="_blank" ><%= image_tag("ppt.png",  :class =>"img-responsive addNew ") %></a>
			        <% end %>
          </div>
        </div>
      </div>
      <div class="formSection">
        <div class="form-group">
          <label for="title" class="required">Title</label>
          <%= f.text_field :name,class: 'form-control', :placeholder => "Title" %>
        </div>
        <div class="form-group">
          <label for="description">Description</label>
          <%= f.text_area :description, class:'form-control' %>
        </div>
        <div class="form-group">
          <label for="folder" class="required">Folder</label>
          <%= f.select(:folder, @all_folders.map{ |value| [ value.name, value.name ] }, {}, { :class => 'form-control folderlist' }) %>
        </div>
        <div class="form-group">
          <label for="tags">Tags</label>
            <input id="input-tag" class="form-control" type="text" data-role="tagsinput" value="<%= @content_item.tags %>"/>
          
          
          <%= f.hidden_field :tags ,class: 'tags_field' %>
        </div>
      </div>
      
      <div class="formSection">
        <div>
          <b style="cursor:pointer" onclick="toggleMappingPnl()">
            <%= image_tag("maximize.png", alt: "Rails logo",class: "collapseImg") %><%= image_tag("expand.png", alt: "Rails logo",class: "expandImg") %>CRM Mapping</b>
        </div>
        <div class="crmmapping" style="margin-top:10px">
          <div class="form-group">
            <label for="persona">Opportunity Stage</label>
            <%= f.select(:stage, @opp_stage_list.map{ |value| [ value, value ] }, {include_blank: '---None---'}, { :class => 'form-control' }) %>
            
          </div>
        </div>
      </div>
      <div style="text-align:right" class="btnPnl">
        <button type="submit"  class="btn btn-primary" onclick="settags()">Save</button>
        <%= link_to  '<button type="button" class="btn btn-danger">Delete</button>'.html_safe, @content_item, method: :delete, data: { confirm: 'Are you sure?' }, class:"myBtn" %>
      </div>
      <br><br>
     <% end %>
  </div>
</div>
</div>
<script>
    $(document).ready(function(){
      toggleNavmenu();
      toggleVedioPnl();
      
      $(".contentUrl").bind("change", function() {
        toggleVedioPnl();
      });
      
      $('.menu li a').click(function(){
        $('.menu li').removeClass('active');
        $(this).parent().addClass('active');
      });
       $("#input-tag").tagsinput('items');
    });
    
  function toggleVedioPnl(){
    if($(".contentUrl").val() != undefined && $(".contentUrl").val() !=''){
      $("#contentFrame").attr('src',$(".contentUrl").val());
      $(".vedioRow").show();
    }else{
      $(".vedioRow").hide();
    }
  }
      
      
function toggleMappingPnl(){
  $(".crmmapping").toggle();
  $(".expandImg").toggle();
  $(".collapseImg").toggle();
}
function settags(){
  $(".tags_field").val($("#input-tag").val());
  
}
</script>

app/views/content_items/index.html.erb
<style>
.navmenu-default .navmenu-nav.dropdown-menu, .navbar-default .navbar-offcanvas .navmenu-nav.dropdown-menu {
			background-color: #f8f8f8;
		}
		 .menu ul {
      list-style-type: none;
      margin: 0;
      padding: 0;
      overflow: hidden;
      background-color: #f3f3f3;
    }
    
   .menu li {
        float: left;
        
    }
   
		body{
			padding-top:55px !important;
		}
		.top-menu{
			background-color: #e7e7e7;
		}
		
		.content-row {
			background-color: #fff;
			margin-top: 20px;					
		}
		.content-info{
			min-height:70px;
		}
		.content-info h4 {
			color: black;
			font-size:17px;
		}
		.content-info h5 {
			color: grey;
			font-size: 13px;
		}
		.img-icon {
			left: 50%;
			margin-left: -20px !important;
			margin-top: -20px !important;
			position: absolute;
			top: 50%;
			width: 40px;
			z-index: 99;
		}
</style>
<div style="border:0px;margin-bottom:0px;" class="navbar menu">
  <ul class="row navbar-nav" style="width:100%">
    <li class="col-xs-12 col-md-offset-2 col-md-8" style="font-weight:bold;padding: 10px 0px 10px 20px;font-size: 14px;">
     Content List 
    </li>  
  </ul>
 </div>
<div class="container-fluid">
	
		
	<div class="row ">
		<div class="content-row col-xs-12 col-md-offset-2 col-md-8">
			<table class="table">
				<% @content_items.each do |content_item| %>
				<tr>
					<td>
						<div class="col-lg-2 col-xs-4">
						  <a href="/content_items/<%= content_item.id%>/edit">
  						  <% if content_item.attachment_url.blank? %>
  						  	<% if !content_item.thumbnail.blank? %>
  						  	<%= image_tag("play-icon.png",  :class =>"img-icon img-responsive") %>
  								<img src="<%= content_item.thumbnail %>" class="img-responsive">
  								<% end %>
  						  <% elsif content_item.attachment_url.include? ".pdf" %>
									<%= image_tag("Pdf.png",  :class =>"img-responsive addNew ") %>
								<% elsif content_item.attachment_url.include? ".ppt" %>
									<%= image_tag("ppt.png",  :class =>"img-responsive addNew ") %>
								<% end %>
  						</a>
						</div>
						<div class="col-lg-6 col-xs-8 content-info" >
							<h4><a href="/content_items/<%= content_item.id%>/edit" ><%= content_item.name %></a></h4>
							<h5>Uploaded <%= content_item.created_at.strftime("%m/%d/%y") %> 
							<% if !content_item.user.blank? %>
							by <%= content_item.user.name %>
							<% end %>
							<% if !content_item.attachment_url.blank? %>
								&nbsp;<%= number_to_human_size(content_item.attachment.file.size) %>
							<% end %>
							</h5>
							
						</div>
					</td>
				</tr>
				<% end %>
			</table>
		</div>
	</div>
</div>

app/views/content_items/new.html.erb
<style>
  .inner-addon { 
      position: relative; 
  }
  
  /* style icon */
  .inner-addon .glyphicon {
    position: absolute;
    padding: 10px;
    pointer-events: none;
  }
  
  /* align icon */
  .left-addon .glyphicon  { left:  0px;}
  .right-addon .glyphicon { right: 0px;}
  
  /* add padding  */
  .left-addon input  { padding-left:  30px; }
  .right-addon input { padding-right: 30px; }
  .vedioRow{
    padding:16px;
    paddin-top:0px;
    display:none;
  }
  .formSection{
    background-color:#EEEEEE;
    padding: 4px;
    margin-top:1px;
  }
  .btnPnl{
    margin-top:30px;
  }
  .btnPnl .btn{
      width: 125px;
  }
  .headerRow{
    background-color:#EEEEEE;
  }
    .menu ul {
      list-style-type: none;
      margin: 0;
      padding: 0;
      overflow: hidden;
      background-color: #f3f3f3;
    }
    
   .menu li {
        float: left;
        text-align:center;
    }
    
    .menu li a {
        display: inline-block;
        color: #666;
        text-align: center;
        padding: 10px 0px;
        text-decoration: none;
        text-transform: uppercase;
    }
    
    .menu li a:hover {
        background-color: #f3f3f3;
    }
    .collapseImg{
      display:none;
    }
</style>
<div class="navbar menu" style="border:0px;margin-bottom:0px;margin-top:46px;">
  <ul class="row">
      <li class="col-xs-2"><a href="#">Add New</a></li>
      <li class="col-xs-2 active"><a href="#" style="color:#639498 "><span class="glyphicon glyphicon-play-circle"></span> Vedio</a></li>
      <li class="col-xs-2"><a href="#" style="color:#7BA439"><span class="glyphicon glyphicon-blackboard"></span>  Presentation</a></li> 
      <li class="col-xs-2"><a href="#" style="color:#7C7996"><span class="glyphicon glyphicon-link"></span> Link</a></li> 
      <li class="col-xs-2"><a href="#" style="color:#FBA127"><span class="glyphicon glyphicon-camera"></span> Image</a></li> 
      <li class="col-xs-2"><a href="#" style="color:#E2B7BB"><span class="glyphicon glyphicon-file"></span> Document</a></li>
    </ul>
</div>
<div class="container-fluid">
  
<div class="row">
  <div class="col-xs-12 col-md-offset-2 col-md-8">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <% if @content_item.errors.any? %>
    <div>
      <div class="alert alert-danger">
        The form contains <%= pluralize(@content_item.errors.count, "error") %>.
        <ul>
      <% @content_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
      </div>
      
    </div>
  <% end %>
    <%= form_for @content_item, :url => {:action => "savecontent"} do |f| %>
      <div class="form-group">
        <div class="inner-addon left-addon">
          <i class="glyphicon glyphicon-search"></i>
          <%= f.text_field :url,class: 'form-control contentUrl', :placeholder => "URL" %>
        </div>
        <div class="row vedioRow" >
          <div class="col-xs-12 col-md-10" style="padding:0px">
            <iframe id="contentFrame" width="100%" height="315" style="border: 0px;"
              src="">
            </iframe>
          </div>
        </div>
      </div>
      <div class="formSection">
        <div class="form-group">
          <label for="title" class="required">Title</label>
          <%= f.text_field :name,class: 'form-control', :placeholder => "Title" %>
        </div>
        <div class="form-group">
          <label for="description">Description</label>
          <%= f.text_area :tags, class:'form-control' %>
          
        </div>
        <div class="form-group">
          <label for="folder" class="required">Folder</label>
          <%= f.select(:folder, ['Trending Videos', 'Value Prop','Competitive','Persona Messages'],  {include_blank: '---None---'}, { :class => 'form-control' }) %>
        </div>
        <div class="form-group">
          <label for="type">Type</label>
          <%= f.select(:content_type, ['Whitepaper', 'PPT','Customer Story','Competitive'], {include_blank: '---None---'}, { :class => 'form-control' }) %>
        </div>
        
        <div class="form-group">
          <label for="buyingstage">Buying Stage</label>
          <%= f.select(:buying_stage, ['Whitepaper', 'PPT','Customer Story','Competitive'], {include_blank: '---None---'}, { :class => 'form-control' }) %>
          
        </div>
        <div class="form-group">
          <label for="persona">Persona</label>
          <%= f.select(:persona, ['VP Sales', 'CMO', 'Product Marketing', 'Sales Ops', 'Sales Reps','Sales Managers', 'Solution Consultants'], {include_blank: '---None---'}, { :class => 'form-control' }) %>
        </div>
        <div class="form-group">
          <label for="persona">Industry</label>
          <%= f.select(:industry, ['Finance', 'Technology', 'Telco', 'Retail', 'Manufacturing','Pharma', 'Oil&Gas'], {include_blank: '---None---'}, { :class => 'form-control' }) %>
        </div>
      </div>
      
      <div class="formSection">
        <div>
          <b style="cursor:pointer" onclick="toggleMappingPnl()">
            <%= image_tag("maximize.png", alt: "Rails logo",class: "collapseImg") %><%= image_tag("expand.png", alt: "Rails logo",class: "expandImg") %>CRM Mapping</b>
        </div>
        <div class="crmmapping" style="margin-top:10px">
          <div class="form-group">
            <label for="persona">Opportunity Stage</label>
            <%= f.select(:stage, @opp_stage_list.map{ |value| [ value, value ] }, {include_blank: '---None---'}, { :class => 'form-control' }) %>
            
          </div>
        </div>
      </div>
      <div style="text-align:right" class="btnPnl">
        <%= f.submit "Save", class: "btn btn-primary" %>
        
        <%= link_to '<button type="button" class="btn btn-danger">Cancel</button>'.html_safe, home_path, class:"myBtn" %>
      </div>
      
     <% end %>
  </div>
</div>
</div>
<script>
$(document).ready(function(){
      toggleVedioPnl();
      $(".contentUrl").bind("change", function() {
        toggleVedioPnl();
      });
      function toggleVedioPnl(){
        if($(".contentUrl").val() != undefined && $(".contentUrl").val() !=''){
          $("#contentFrame").attr('src',$(".contentUrl").val());
          $(".vedioRow").show();
        }else{
          $(".vedioRow").hide();
        }
      }
});
function toggleMappingPnl(){
  $(".crmmapping").toggle();
  $(".expandImg").toggle();
  $(".collapseImg").toggle();
  
}
</script>

app/views/content_items/show.html.erb
<br/><br/><br/><br/>
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @content_item.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @content_item.url %>
</p>

<p>
  <strong>Folder:</strong>
  <%= @content_item.folder %>
</p>

<p>
  <strong>Type:</strong>
  <%= @content_item.content_type %>
</p>

<p>
  <strong>Tags:</strong>
  <%= @content_item.tags %>
</p>
<p>
  <strong>Tags:</strong>
  <%= @content_item.stage %>
</p>

<%= link_to 'Edit', edit_content_item_path(@content_item) %> |
<%= link_to 'Back', content_items_path %>