config/routes.rb
Rails.application.routes.draw do
  get 'readiness_events/index'

  root 'pages#login' # rout
  get 'home'    => 'pages#home'
  
  get 'newcontent' => 'pages#newcontent'
  post 'pages/savecontent' => 'pages#savecontent'
  post 'addfolder' => 'pages#addfolder'
  post 'geturlinfo' => 'pages#geturlinfo'
  
  get 'viewcontent' => 'pages#viewcontent'
  get 'readinessevent' => 'pages#readinessevent'
  post 'pages/save_readiness_event' => 'pages#save_readiness_event'
  patch 'pages/save_readiness_event' => 'pages#save_readiness_event'
  
  get 'checkreadiness' => 'pages#checkreadiness'
  post 'save_check_readiness' => 'pages#save_check_readiness'
  get 'cancelreadiness' => 'pages#cancelreadiness'
  
  get 'readinessactivity' => 'pages#readinessactivity'
  get 'userlist' => 'pages#userlist'
  get 'faqlist' => 'pages#faqlist'
  post 'pages/savefaq' => 'pages#savefaq'
  
  get 'dashboard' => 'pages#dashboard'
  
  resources :content_items  , only: [:index, :edit, :update, :destroy]
  resources :readiness_events  , only: [:index, :edit, :update, :destroy]
  
  #salesforce authentication
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'pages#logout', as: 'signout', via: [:get, :post]

  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
	  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	  <meta http-equiv="X-Frame-Options" content="GOFORIT">
	  <% if yield(:url) !='' %>
	  <meta property="og:url" content="<%= yield(:url) %>">
    <meta property="og:title" content="<%= yield(:title) %>">
    <meta property="og:image" content="<%= yield(:image) %>">
    <meta property="og:description" content="<%= yield(:description) %>">
	  <% end %>
    <title>Salesica</title>
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css' => true %> 
    <%= javascript_include_tag 'https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js', 'data-turbolinks-track' => true %>
    
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
    <style>
    body{
      	
      	font-family: "Helvetica Neue", Helvetica, Arial, sans-serif !important;
      }
      .navbar-salesica {
      	background: #3498db none repeat scroll 0 0;
      	box-shadow: 0 1px 2px #888888;
      	width: 100%;
      }
      .product {
      	border: 1px solid #dddddd;
      	display: block;
      	height: auto;
      	background-color: #fff;
      }
      .image a img {
      	margin: 0 auto;
      	max-height: 190px;
      }
      .image {
      	display: block;
      	max-height: 240px;
      	overflow: hidden;
      	position: relative;
      	text-align: center;
      
      }
      .description {
      	margin: 10px;
      	max-width: 235px;
      }
      .price {
      	color: #454545;
      	font-size: 18px;
      	font-weight: bold;
      }
      .action-control {
      	border: 0 none;
      	display: block;
      	height: auto;
      	width: 100%;
      }		
      .item h4 a {
      	color: #337ab7;
      	font-family: "Source Sans Pro",sans-serif;
      	font-size: 14px;
      	font-weight: 500;
      	text-decoration: none;
      	
      }
      .item h4{
      	font-family: "Source Sans Pro",sans-serif;
      	font-size: 14px;
      	font-weight: 500;
      	text-decoration: none;
      }
      #owl-slider .item img{
      	display: block;
      	width: 100%;
      	height: 300px;
      }
      legend{
      	height:3px;
      	background-color: #fff;
      }
      
      .add-fav .glyphicon-heart{
      	font-size: 20px;
      	padding: 15px;
      }
      .date{
      	margin : 5%;
      }
      
      .action-control a {
      	color: darkgrey;
      	text-decoration: none;
      }
      
      .searchbox {
      	position: relative;
      	width:100%;
      	z-index: 999;
      	top:150px;
      }
      
      
      
      
      /*************** Menu ***************/
      
      .navbar-default .navbar-toggle:focus, .navbar-default .navbar-toggle:hover{
      	background-color:none !important;
      }
      .navbar-toggle{
      	border:none;
      }
      .navbar-toggle .icon-bar {
      	border: 2px solid #fff;
      }
      .addContent {
      	color: #fff;
      	font-size: 15px;
      }
      .navbar-offcanvas{
      	overflow-y:auto;
      }
      .offcanvas-toggle {
      	background: rgba(0, 0, 0, 0) none repeat scroll 0 0;
      }
      body {
       padding-top: 56px !important;
      }
      @media screen and (max-width: 440px) {
       .mobile-first-column{
        width:0;
       }
       .mobile-second-column{
         width:45% !important;
       }
       .mobile-third-column{
       
       }
      }
      .search_field{
        border-radius:0;border-right:0;
      }
    </style>
    <script>
      function toggleNavmenu(){
        $('.navmenu').on('hide.bs.offcanvas', function (e) {
        	//if (!data) return e.preventDefault() // stops menu from being shown
        	console.log('hide');
        	//setTimeout(function(){ $('.layOver').hide(); }, 500);
        });
      
        $('.navmenu').on('show.bs.offcanvas', function (e) {
        	//if (!data) return e.preventDefault() // stops menu from being shown
        	console.log('show');
        	//$('.layOver').show();
        });
      }
    
    </script>
  </head>
  <body>
    
    <div class="navmenu navmenu-default navmenu-fixed-left offcanvas">
      <ul class="nav navmenu-nav">
        <li><a href="#">&nbsp; <span class="icons fa fa-pencil"></span> &nbsp;&nbsp; Assistant</a></li> 
    		<li class="content"><%= link_to '&nbsp; <span class="icons fa fa-file-text-o"></span> &nbsp;&nbsp; Content'.html_safe, home_path %></li> 
    		<li class="readiness"><%= link_to '&nbsp; <span class="icons fa fa-check"></span> &nbsp;&nbsp; Readiness'.html_safe, readinessactivity_path %></li> 
    		<li><a href="#">&nbsp; <span class="icons fa fa-line-chart"></span> &nbsp;&nbsp; Analytics</a></li> 
    		<% if !current_user.blank? && current_user.allow_admin ==true %>
    		  <li class="dropdown open">
          	<a aria-expanded="true" aria-haspopup="true" role="button" data-toggle="dropdown" class="dropdown-toggle" href="#">
          	&nbsp; <span class="icons fa fa-user"></span> &nbsp;&nbsp; Admin
          	<span class="caret"></span>
          	</a>
          	<ul class="dropdown-menu nav navmenu-nav">
          		<li><a href="/content_items">&nbsp; &nbsp; &nbsp; Content</a></li>
          		<li><a href="/readiness_events">&nbsp; &nbsp; &nbsp; Readiness Activities</a></li>
          		<li><a href="/userlist">&nbsp; &nbsp; &nbsp; Users</a></li>   
          		<li><%= link_to '&nbsp; &nbsp; &nbsp; FAQ'.html_safe, faqlist_path %></li>
          	</ul>
          </li>
    		<% end %>
    		<li><a href="#">&nbsp; <span class="icons fa fa-info-circle"></span> &nbsp;&nbsp; Help</a></li> 
    		<li><%= link_to '&nbsp; <span class="icons fa fa-sign-out"></span> &nbsp;&nbsp; Logout'.html_safe, signout_path %></li> 
    		
      </ul>
    </div>

	
    <!-- Fixed navbar -->
    <nav class="navbar navbar-salesica navbar-fixed-top">
        <div class="container-fluid" style="padding:0">
    			<!-- Mobile view -->
    			<div class="navbar-header">
    			  <button type="button" class="navbar-toggle pull-left collapsed" data-toggle="offcanvas" data-target=".navmenu" data-canvas="body">
      				<span class="icon-bar"></span>
      				<span class="icon-bar"></span>
      				<span class="icon-bar"></span>
    			  </button>
    			  <span class="search_panel" style="display:none">
      			  <%= form_tag(home_path, :method => "get",  id: "search-form") do %>
	              <div class="col-xs-1 visible-xs-block mobile-first-column" style="padding:0; margin-top:10px"></div>
                <div class="col-xs-6 visible-xs-block mobile-second-column" style="padding:0; margin-top:10px;">
                  <%= text_field_tag :search, params[:search], class: "form-control search_field", placeholder: "What are you looking for?" %>
                </div>
                <div class="col-xs-1 visible-xs-block mobile-third-column" style="padding:0; margin-top:10px">
                    <button class="btn btn-success" style="border-radius:0;border-left:0;"> Find </button>
                </div>
              <% end %>
    			  </span>
    			  <a class="visible-xs-block navbar-toggle" style="padding:0;margin-left:0">
      				<% if !current_user.blank? %>
      				    <img src="<%= current_user.profile_image %>" height="38" style="padding:3px"/>
    				    <% end %>
      				
    			  </a>
  		  	</div>
		
  		  	<!-- Small , Medium , Large device view -->
    			<div id="navbar" class="navbar-collapse collapse">
    			  <button type="button" class="visible-sm-block visible-md-block visible-lg-block navbar-toggle pull-left collapsed" data-toggle="offcanvas" data-target=".navmenu" data-canvas="body">
      				<span class="icon-bar"></span>
      				<span class="icon-bar"></span>
      				<span class="icon-bar"></span>
    			  </button>
    			  <span class="search_panel" style="display:none">
      			  <%= form_tag(home_path, :method => "get",  id: "search-form") do %>
        			  <div class="col-lg-3 col-md-3 col-sm-2" style="padding:0; margin-top:10px"></div>
                <div class="col-lg-4 col-md-4 col-sm-5" style="padding:0; margin-top:10px">
                    <%= text_field_tag :search, params[:search], class: "form-control search_field", placeholder: "What are you looking for?" %>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-2" style="padding:0; margin-top:10px">
                    <button class="btn btn-success" style="border-radius:0;border-left:0;"> Find </button>
                </div>
              <% end %>
            </span>
    			   <a class="visible-lg-block visible-md-block visible-sm-block navbar-toggle" style="padding:0">
      				  <% if !current_user.blank? %>
      				    <img src="<%= current_user.profile_image %>" height="38"/>
    				    <% end %>
      			 </a>
    			  
    			</div>
		    </div>
      </nav>
    
      <%= yield %>
   
  </body>
</html>